accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import (
login, logout, password_reset, password_reset_done, password_reset_confirm)

app_name = 'accounts'
urlpatterns = [
    url(r'login/$', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'logout/$', logout, {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^register/$', views.register, name = 'register'),
    url(r'^profile/$', views.view_profile, name= 'view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name= 'edit_profile'),
    url(r'^change-password/$', views.change_password, name= 'change_password'),
    url(r'^profile/password/$', views.change_password, name= 'change_password'),
    url(r'^reset-password/$', password_reset, name='reset_password'),
    url(r'^reset-password/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset-password/confirm/$', password_reset_confirm, name='password_reset_confirm'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    email = models.EmailField(default='')

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user = kwargs['instance'])


post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
    #email = forms.EmailField(required = True)

    class Meta:
        model = User
        fields = (
        'username'
        ,'email'
        ,)

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        # user.first_name = self.cleaned_data['first_name']
        # user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            print(user.email)
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email'
            ,'first_name'
            ,'last_name'
            ,'password')
        exclude = ()

accounts/views.py
from django.shortcuts import render, redirect
from accounts.forms import RegistrationForm, EditProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, login, authenticate
from django.contrib.auth.decorators import login_required
# import stripe
import sys
# import request

pub_key = "pk_test_JQjapwoMEXZYA01fnjDTBQaV"
secret_key = "sk_test_x5RMbDg4B2MKf8hh1ysaWuBY"
# stripe.api_key = secret_key

def register(request):

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            # for i in request.POST:
            #     print(i)
# prod_CMQhlNvWEC1GTB
            # try:
            email= request.POST['stripeEmail']
            source= request.POST['stripeToken']
            # user.email = email
            user = form.save()

            for i in request.POST:
                print(i)
            customer = stripe.Customer.create(
                email=user.email,
                # plan = 'prod_CNva2YwamwS3D0',
                card = request.POST['stripeToken']
                #user.stripe_id,
                # card = form.cleaned_data['stripe_id'],
            )

            charge = stripe.Charge.create(
                customer=customer.id,
                amount=1999,
                currency="USD",
                description='test',
                # source=request.POST['stripeToken']
            )
            print("Customer id is : " + customer.id)

            subscription = stripe.Subscription.create(
            customer=customer.id,
            items=[{'plan': 'test'}],
            )
            user.stripe_id = customer.id
            user.save()

            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('/saferdb/query')

            # except stripe.CardError e:
            #     form.add_my_error("Card has been declined.")
        # except ImportError:
        #         print('shit failed')
        #         form = RegistrationForm(request.POST)
        #         args = {'form': form, 'pub_key': pub_key}
        #         return render(request, 'accounts/reg_form.html', args)
        else:
            form = RegistrationForm(request.POST)
            args = {'form': form, 'pub_key': pub_key}
            return render(request, 'accounts/reg_form.html', args)
    else:
        form = RegistrationForm(request.POST)
        args = {'form': form, 'pub_key': pub_key}#
        return render(request, 'accounts/reg_form.html', args)

# @login_required
def view_profile(request):
    args = {'user': request.user}
    return render(request, 'accounts/profile.html', args)
# @login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user )

        if form.is_valid():
            form.save()
            return redirect('/accounts/profile')
        else:
            form = EditProfileForm(instance=request.user)
            args = {'form': form}
            return render(request, 'accounts/edit_profile.html', args )
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args )

def cancel_subscription(request):
    #try:
    customer = stripe.Customer.retrieve(request.user.stripe_id)
    customer.cancel_subscription(at_period_end=True)

    # except Exception e:
    # messages.error(request, e)
    return render(request, '')

def change_password(request):
        if request.method == 'POST':
            form = PasswordChangeForm(data=request.POST, user=request.user )

            if form.is_valid():
                form.save()
                update_session_auth_hash(request, form.user)
                return redirect('/accounts/profile')
            else:
                return redirect('/account/change-password')
        else:
            form = PasswordChangeForm(user=request.user)

            args = {'form': form}
            return render(request, 'accounts/change_password.html', args )

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}
{% block body %}
<div class="container">
<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" >Submit</button>

</form>

{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}
{% block body %}
<div class="container">
<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" >Submit</button>

</form>

<button type="button" class="btn" name="button">Cancell Subscription</button>
{% endblock %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}
<h1>Home</h1>
{% block head %}
<title>Home</title>
{% endblock %}

{% block body %}
<h1>Home</h1>
{% endblock %}

accounts/templates/accounts/login.html
<!DOCTYPE html>

<html>

<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<title>USDOT Search</title>



<body class="text-center">
          <p class="display-6">BlockQuote the Gathering</p>

          <!-- <h3>Log In</h3> -->
          <form method="post">

          {% csrf_token %}
          {{ form.as_p }}
          <button class="btn btn-primary" type="submit">Login</button>
          <a class="btn btn-primary" href="{% url 'accounts:register' %}">Register</a>
        </form>

</body>

<!-- Script: Animated entrance -->
<!-- <script type="application/javascript"src="{% static 'saferdb/animate-in.js' %}"></script> -->


<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
<script type="application/javascript" src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script type="application/javascript" src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script type="application/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script>

  $(document).ready(function() {
    $(document).ready(function() {
      $(".navbar-header").parent().css("background-color", "#e1261c");
      $(".navbar-collapse").css("background-color", "#e1261c");
      $(".navbar-collapse").parent().css("background-color", "#e1261c");


      $(".white_anchor").css("color", "white");
      $(".pillars").css("background-color", "#e1261c");
      $(".pillars").css("color", "white");
      // $("#id_password").hide();

    });
  });
</script>
<link rel="stylesheet" href="{% static 'saferdb/aquamarine.css' %}" type="text/css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">

</html>

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Logged Out!</h1>
    <p>
        Comeback soon!
    </p>

</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}
{% block body %}
<div class="container">
  <p>
  User Name: {{ user }}<br>
  First Name: {{user.first_name}}<br>
  Last Name: {{user.last_name}}<br>

  Email: {{user.email}}


</p>
</div>

{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}


{% block body %}
<div class="container">
  <!-- <h1>Register</h1> -->
  <!-- <form method="post">
    {% csrf_token %}
  </form> -->
  <p class="h4">
    <small><i>Please note this site is 95% complete. If you create an account you will have access to a partial DOT database.<br>
      You can use the test credit card number: 4242 4242 4242 4242 until the site is 100% complete by mid April.
      Thank you, all we ask is you provide us some feed back at:</i></small>

    <a href="mailto:DOTsearch.feedback@lev.one?Subject=Feedback" target="_top">DOTsearch.feedback@lev.one</a>

  </p>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <!-- <button type="submit">Register</button> -->
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_JQjapwoMEXZYA01fnjDTBQaV"
    data-amount="1999"
    data-name="boxtrucks.herokuap"
    data-description="Widget"
    data-zip-code="true"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto">
  </script>
</form>

</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
$( document ).ready(function() {
$(document).ready(function(){
    $(".errorlist").css("color", "#e1261c");

});
});

</script>

{% endblock %}